import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title:{
    absolute: "",
    default: "Learning Next.js",
    template: "%s | Learning Next.js",
  },
  description: "Generated by create next app",

}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="text-3xl bg-blue-500 h-[50px] flex justify-center items-center">
          <h1>Header</h1>
        </header>
        <main className="min-h-[calc(100vh-100px)] flex flex-col justify-center items-center ">
        {children}
        </main>
        <footer className="text-3xl bg-gray-500 h-[50px] flex justify-center items-center">
          <h1>Footer</h1>
        </footer>
        </body>
    </html>
  );
}
